plugins {
    id 'java-library'
}

group = 'com.splitwise'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-json:3.2.0'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

//plugins {
//    id 'java'
//}
//
//group = 'com.splitwise'
//version = '1.0-SNAPSHOT'
//
//repositories {
//    mavenCentral()
//}
//
//plugins {
//    id 'java-library'
//}
//
//dependencies {
//    testImplementation platform('org.junit:junit-bom:5.10.0')
//    testImplementation 'org.junit.jupiter:junit-jupiter'
//
//    api 'org.springframework.boot:spring-boot-starter-json'
//    compileOnly 'org.projectlombok:lombok:1.18.30'
//    annotationProcessor 'org.projectlombok:lombok:1.18.30'
//}
//
//test {
//    useJUnitPlatform()
//}